#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "directly push on main branch is not allowed"
  exit 1
fi

yarn lint

# yarn package 에 lint 명령어가 들어가 있어야 한다.
# e.g. eslint "{src,apps,libs,test}/**/*.ts" --fix
