/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/**/*.stories.tsx',
    './node_modules/bbodek-ui/dist/**.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        white: '#fff',
        black: '#101828',
        'gray-09': '#F5F5F5',
        'gray-08': '#1C273E',
        'gray-07': '#333D52',
        'gray-06': '#7C8497',
        'gray-05': '#A9B2C7',
        'gray-04': '#8588A1',
        'gray-03': '#DBE1ED',
        'gray-02': '#EAEEF6',
        'gray-01': '#EFF2F9',
        'gray-00': '#F8FAFF',
        'primary-06': '#002F75',
        'primary-05': '#003C96',
        'primary-04': '#004DC0',
        'primary-03': '#206FE4',
        'primary-02': '#3D89FA',
        'primary-01': '#9DC5FF',
        'primary-00': '#DEEBFF',
        error: '#FF5260',
        warning: '#FFBB6A',
        success: '#79D4B4',
        transparent: 'transparent',
      },
      fontSize: {
        'head-01-regular': [
          '1.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'head-01-medium': [
          '1.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'head-01-bold': [
          '1.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'head-02-regular': [
          '1.5rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'head-02-medium': [
          '1.5rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'head-02-bold': [
          '1.5rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'subhead-01-regular': [
          '1.25rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'subhead-01-medium': [
          '1.25rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'subhead-01-bold': [
          '1.25rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'subhead-02-regular': [
          '1.125rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'subhead-02-medium': [
          '1.125rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'subhead-02-bold': [
          '1.125rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'body-01-regular': [
          '1rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'body-01-medium': [
          '1rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'body-01-bold': [
          '1rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'body-02-regular': [
          '0.875rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'body-02-medium': [
          '0.875rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'body-02-bold': [
          '0.875rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
        'body-03-regular': [
          '0.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'body-03-medium': [
          '0.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '500',
          },
        ],
        'body-03-bold': [
          '0.75rem',
          {
            lineHeight: '1.5',
            fontWeight: '700',
          },
        ],
      },
      boxShadow: {
        section: '0 .25rem 1.25rem .25rem rgba(0, 0, 0, 0.04)',
      },
      animation: {
        'fade-in': 'fade-in .2s cubic-bezier(0, 0, 0.5, 1)',
        popup: 'popup .2s cubic-bezier(0, 0, 0.5, 1)',
        drawer: 'drawer .2s cubic-bezier(0, 0, 0.5, 1)',
        'bottom-sheet': 'bottom-sheet .2s cubic-bezier(0, 0, 0.5, 1)',
      },
      borderRadius: {
        default: '1.25rem',
      },
      fontFamily: {
        pretendard: ['Pretendard'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        popup: {
          '0%': { transform: 'translateY(16px)' },
          '100%': { transform: 'translateY(0)' },
        },
        drawer: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'bottom-sheet': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
    },
  },
  safelist: [
    // text levels
    'text-head-01-regular',
    'text-head-01-medium',
    'text-head-01-bold',
    'text-head-02-regular',
    'text-head-02-medium',
    'text-head-02-bold',
    'text-subhead-01-regular',
    'text-subhead-01-medium',
    'text-subhead-01-bold',
    'text-subhead-02-regular',
    'text-subhead-02-medium',
    'text-subhead-02-bold',
    'text-body-01-regular',
    'text-body-01-medium',
    'text-body-01-bold',
    'text-body-02-regular',
    'text-body-02-medium',
    'text-body-02-bold',
    'text-body-03-regular',
    'text-body-03-medium',
    'text-body-03-bold',

    // text colors
    'text-white',
    'text-black',
    'text-gray-09',
    'text-gray-08',
    'text-gray-07',
    'text-gray-06',
    'text-gray-05',
    'text-gray-04',
    'text-gray-03',
    'text-gray-02',
    'text-gray-01',
    'text-gray-00',
    'text-primary-06',
    'text-primary-05',
    'text-primary-04',
    'text-primary-03',
    'text-primary-02',
    'text-primary-01',
    'text-primary-00',
    'text-error',
    'text-warning',
    'text-success',
    'text-transparent',

    // background colors
    'bg-white',
    'bg-black',
    'bg-gray-09',
    'bg-gray-08',
    'bg-gray-07',
    'bg-gray-06',
    'bg-gray-05',
    'bg-gray-04',
    'bg-gray-03',
    'bg-gray-02',
    'bg-gray-01',
    'bg-gray-00',
    'bg-primary-06',
    'bg-primary-05',
    'bg-primary-04',
    'bg-primary-03',
    'bg-primary-02',
    'bg-primary-01',
    'bg-primary-00',
    'bg-error',
    'bg-warning',
    'bg-success',
    'bg-transparent',

    // border colors
    'border-white',
    'border-black',
    'border-gray-09',
    'border-gray-08',
    'border-gray-07',
    'border-gray-06',
    'border-gray-05',
    'border-gray-04',
    'border-gray-03',
    'border-gray-02',
    'border-gray-01',
    'border-gray-00',
    'border-primary-06',
    'border-primary-05',
    'border-primary-04',
    'border-primary-03',
    'border-primary-02',
    'border-primary-01',
    'border-primary-00',
    'border-error',
    'border-warning',
    'border-success',
    'border-transparent',

    // fill colors
    'fill-white',
    'fill-black',
    'fill-gray-09',
    'fill-gray-08',
    'fill-gray-07',
    'fill-gray-06',
    'fill-gray-05',
    'fill-gray-04',
    'fill-gray-03',
    'fill-gray-02',
    'fill-gray-01',
    'fill-gray-00',
    'fill-primary-06',
    'fill-primary-05',
    'fill-primary-04',
    'fill-primary-03',
    'fill-primary-02',
    'fill-primary-01',
    'fill-primary-00',
    'fill-error',
    'fill-warning',
    'fill-success',
    'fill-transparent',

    // placeholder colors
    'placeholder-white',
    'placeholder-black',
    'placeholder-gray-09',
    'placeholder-gray-08',
    'placeholder-gray-07',
    'placeholder-gray-06',
    'placeholder-gray-05',
    'placeholder-gray-04',
    'placeholder-gray-03',
    'placeholder-gray-02',
    'placeholder-gray-01',
    'placeholder-gray-00',
    'placeholder-primary-06',
    'placeholder-primary-05',
    'placeholder-primary-04',
    'placeholder-primary-03',
    'placeholder-primary-02',
    'placeholder-primary-01',
    'placeholder-primary-00',
    'placeholder-error',
    'placeholder-warning',
    'placeholder-success',
    'placeholder-transparent',
  ],
};
